### ISSUE TITLE
Problem representing this WMS service

### ISSUE THREAD

**Issue by rsignell-usgs** [chilukey/viewer#1]
We have a model output  dataset from a Unidata THREDDS Data Server on data.gov at
http://catalog.data.gov/dataset/coawst-forecast-system-usgs-us-east-coast-and-gulf-of-mexico-experimental

If you click any of the WMS links (simple or advanced viewer) we get back "can not load map":
![4-23-2015 1-55-42 pm](https://cloud.githubusercontent.com/assets/1872600/7318782/869770fc-ea5d-11e4-9feb-3ec3948375af.png)

Yet it seems that the WMS service is working okay.  This request:
http://geoport-dev.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd?LAYERS=temp&ELEVATION=-0.03125&TIME=2015-04-24T00%3A00%3A00.000Z&TRANSPARENT=true&STYLES=boxfill%2Frainbow&CRS=EPSG%3A4326&COLORSCALERANGE=0%2C30&NUMCOLORBANDS=64&LOGSCALE=false&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=image%2Fpng&SRS=EPSG%3A4326&BBOX=-83.006379190914,31.242026011357,-58.757973988643,55.490431213629&WIDTH=256&HEIGHT=256
produces the image here:
![coawst_4_use_best](https://cloud.githubusercontent.com/assets/1872600/7318832/eeaa8b0c-ea5d-11e4-8bcc-e8ed23df9f18.png)

Do you know what the issue is with this WMS service in the viewer?

**Comment by kliu4** [comment]
thanks for the reporting. 

The WMS file is big so it needs longer time to download the GetCapabilities file and load the map. I have changed the time limit from 20000 to 60000, so it should be able to load such map services.

However, 

I plan to create a cachestore to store such 'big' or slow services to local. And a scheduler will be running everyday to update the cachestore.  It can make the loading fast. However, since the schedule is daily it may have problem to show the latest change if you have updated the service in the previous 24 hours. 

How do you think?

**Comment by rsignell-usgs** [comment]
this model updates only every 24 hours, so loading every day would be fine.

The model is now visualizing okay on data.gov!

![5-4-2015 9-18-07 am](https://cloud.githubusercontent.com/assets/1872600/7476894/8831b3b8-f31e-11e4-9abd-ed099724a98c.png)
